---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pcidevices
  namespace: harvester-system
  labels:
    app.kubernetes.io/name: pcidevices
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: 0.0.2
spec:
  selector:
    matchLabels:
      name: pcidevices
  template:
    metadata:
      labels:
        name: pcidevices
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: pcidevices
      # hostNetwork: true
      containers:
        - env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          name: network
          image: rancher/harvester-pcidevices:master-head
          imagePullPolicy: Always
          command:
            - pcidevices
          args:
            - agent
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /dev
            name: dev
          - mountPath: /lib/modules
            name: modules
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 50Mi
      volumes:
      - hostPath:
          path: /dev
          type: Directory
        name: dev
      - hostPath:
          path: /lib/modules
          type: Directory
        name: modules
---
apiVersion: v1
kind: Service
metadata:
  name: pcidevices-webhook
  namespace: harvester-system
spec:
  selector:
    name: pcidevices
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443